In [2]:
import pandas as pd

In [6]:
df=pd.read_csv('CleanedDataset.csv')

In [7]:
df['Tweet']=df['Tweet'].str.lower()

In [8]:
df

,Unnamed: 0,id,Time,Tweet,prep,cleaned_tweets
0,0,1.578530e+18,2023-02-13 17:09:44+00:00,b'runny nose tear eyes fever headache loss of ...,runny nose tear eyes fever headache loss of ap...,runny nose tear eyes fever headache loss of ap...
1,1,4.904996e+07,2023-02-13 15:34:08+00:00,b'@katkinneywrites i have hot/cold sometimes. ...,@katkinneywrites i have hot/cold sometimes. us...,i have hot/cold sometimes. usually cold means...
2,2,9.234178e+07,2023-02-13 13:57:31+00:00,b'cytomegalovirus colitis - complication when ...,cytomegalovirus colitis - complication when cd...,cytomegalovirus colitis - complication when cd...
3,3,1.179430e+18,2023-02-13 11:38:54+00:00,b'@fatalkci l know otli and matli for nausea a...,@fatalkci l know otli and matli for nausea and...,l know otli and matli for nausea and vomiting...
4,4,8.566819e+08,2023-02-13 01:57:45+00:00,b'went from a fever to a cough to a sore throa...,went from a fever to a cough to a sore throat ...,went from a fever to a cough to a sore throat ...
...,...,...,...,...,...,...
7475,7475,7.051626e+08,2023-02-05 11:45:11+00:00,b'#nowplaying jump (mega banton) by dengue fev...,#nowplaying jump (mega banton) by dengue fever...,jump (mega banton) by dengue fever riddim on...
7476,7476,6.354304e+07,2023-02-05 11:35:22+00:00,"b""rt @chris_c_chapman: blood counts still very...",rt @chris_c_chapman: blood counts still very l...,rt : blood counts still very low. but they hav...
7477,7477,1.273950e+18,2023-02-05 11:30:20+00:00,b'rt @shukladeepak73: different activities by ...,rt @shukladeepak73: different activities by bc...,rt : different activities by bccf under embed ...
7478,7478,3.306546e+09,2023-02-05 11:26:45+00:00,"b'dengue: 1 more dies, 5 patients hospitalised...","dengue: 1 more dies, 5 patients hospitalised\n...","dengue: 1 more dies, 5 patients hospitalised\n \n"
7479,7479,1.282360e+18,2023-02-05 11:14:11+00:00,"b""if only your name rhymed with dengue shock s...",if only your name rhymed with dengue shock syn...,if only your name rhymed with dengue shock syn...

In [9]:
diseases=['asthma','autism','dengue','fever','flu','nausea','anxiety','sprain','stroke','obesity']

In [10]:
diseases

['asthma',
 'autism',
 'dengue',
 'fever',
 'flu',
 'nausea',
 'anxiety',
 'sprain',
 'stroke',
 'obesity']

In [11]:
tw=[]
for i in df['Tweet']:
    tw.append(i)

In [12]:
len(tw)

7480

In [13]:
tag=[]
flag=False
for i in range(0,len(tw)):
    for j in range(0,len(diseases)):
        if(tw[i].find(diseases[j])>0):
            tag.append(diseases[j])
            flag=True
            break
    if(flag != True):
        tag.append('NIL')
    flag=False

In [14]:
len(tag)

7480

In [15]:
df['tags']=tag

In [16]:
df

,Unnamed: 0,id,Time,Tweet,prep,cleaned_tweets,tags
0,0,1.578530e+18,2023-02-13 17:09:44+00:00,b'runny nose tear eyes fever headache loss of ...,runny nose tear eyes fever headache loss of ap...,runny nose tear eyes fever headache loss of ap...,fever
1,1,4.904996e+07,2023-02-13 15:34:08+00:00,b'@katkinneywrites i have hot/cold sometimes. ...,@katkinneywrites i have hot/cold sometimes. us...,i have hot/cold sometimes. usually cold means...,fever
2,2,9.234178e+07,2023-02-13 13:57:31+00:00,b'cytomegalovirus colitis - complication when ...,cytomegalovirus colitis - complication when cd...,cytomegalovirus colitis - complication when cd...,fever
3,3,1.179430e+18,2023-02-13 11:38:54+00:00,b'@fatalkci l know otli and matli for nausea a...,@fatalkci l know otli and matli for nausea and...,l know otli and matli for nausea and vomiting...,fever
4,4,8.566819e+08,2023-02-13 01:57:45+00:00,b'went from a fever to a cough to a sore throa...,went from a fever to a cough to a sore throat ...,went from a fever to a cough to a sore throat ...,fever
...,...,...,...,...,...,...,...
7475,7475,7.051626e+08,2023-02-05 11:45:11+00:00,b'#nowplaying jump (mega banton) by dengue fev...,#nowplaying jump (mega banton) by dengue fever...,jump (mega banton) by dengue fever riddim on...,dengue
7476,7476,6.354304e+07,2023-02-05 11:35:22+00:00,"b""rt @chris_c_chapman: blood counts still very...",rt @chris_c_chapman: blood counts still very l...,rt : blood counts still very low. but they hav...,dengue
7477,7477,1.273950e+18,2023-02-05 11:30:20+00:00,b'rt @shukladeepak73: different activities by ...,rt @shukladeepak73: different activities by bc...,rt : different activities by bccf under embed ...,dengue
7478,7478,3.306546e+09,2023-02-05 11:26:45+00:00,"b'dengue: 1 more dies, 5 patients hospitalised...","dengue: 1 more dies, 5 patients hospitalised\n...","dengue: 1 more dies, 5 patients hospitalised\n \n",dengue
7479,7479,1.282360e+18,2023-02-05 11:14:11+00:00,"b""if only your name rhymed with dengue shock s...",if only your name rhymed with dengue shock syn...,if only your name rhymed with dengue shock syn...,dengue

In [18]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [19]:
df.head()

,id,Time,Tweet,prep,cleaned_tweets,tags
0,1.578530e+18,2023-02-13 17:09:44+00:00,b'runny nose tear eyes fever headache loss of ...,runny nose tear eyes fever headache loss of ap...,runny nose tear eyes fever headache loss of ap...,fever
1,4.904996e+07,2023-02-13 15:34:08+00:00,b'@katkinneywrites i have hot/cold sometimes. ...,@katkinneywrites i have hot/cold sometimes. us...,i have hot/cold sometimes. usually cold means...,fever
2,9.234178e+07,2023-02-13 13:57:31+00:00,b'cytomegalovirus colitis - complication when ...,cytomegalovirus colitis - complication when cd...,cytomegalovirus colitis - complication when cd...,fever
3,1.179430e+18,2023-02-13 11:38:54+00:00,b'@fatalkci l know otli and matli for nausea a...,@fatalkci l know otli and matli for nausea and...,l know otli and matli for nausea and vomiting...,fever
4,8.566819e+08,2023-02-13 01:57:45+00:00,b'went from a fever to a cough to a sore throa...,went from a fever to a cough to a sore throat ...,went from a fever to a cough to a sore throat ...,fever

In [20]:
df.to_csv('labelled_data.csv')

In [21]:
df['tags'].value_counts()

fever      750
nausea     750
sprain     750
stroke     750
anxiety    750
flu        750
obesity    750
autism     750
asthma     750
dengue     730
Name: tags, dtype: int64

In [22]:
df

,id,Time,Tweet,prep,cleaned_tweets,tags
0,1.578530e+18,2023-02-13 17:09:44+00:00,b'runny nose tear eyes fever headache loss of ...,runny nose tear eyes fever headache loss of ap...,runny nose tear eyes fever headache loss of ap...,fever
1,4.904996e+07,2023-02-13 15:34:08+00:00,b'@katkinneywrites i have hot/cold sometimes. ...,@katkinneywrites i have hot/cold sometimes. us...,i have hot/cold sometimes. usually cold means...,fever
2,9.234178e+07,2023-02-13 13:57:31+00:00,b'cytomegalovirus colitis - complication when ...,cytomegalovirus colitis - complication when cd...,cytomegalovirus colitis - complication when cd...,fever
3,1.179430e+18,2023-02-13 11:38:54+00:00,b'@fatalkci l know otli and matli for nausea a...,@fatalkci l know otli and matli for nausea and...,l know otli and matli for nausea and vomiting...,fever
4,8.566819e+08,2023-02-13 01:57:45+00:00,b'went from a fever to a cough to a sore throa...,went from a fever to a cough to a sore throat ...,went from a fever to a cough to a sore throat ...,fever
...,...,...,...,...,...,...
7475,7.051626e+08,2023-02-05 11:45:11+00:00,b'#nowplaying jump (mega banton) by dengue fev...,#nowplaying jump (mega banton) by dengue fever...,jump (mega banton) by dengue fever riddim on...,dengue
7476,6.354304e+07,2023-02-05 11:35:22+00:00,"b""rt @chris_c_chapman: blood counts still very...",rt @chris_c_chapman: blood counts still very l...,rt : blood counts still very low. but they hav...,dengue
7477,1.273950e+18,2023-02-05 11:30:20+00:00,b'rt @shukladeepak73: different activities by ...,rt @shukladeepak73: different activities by bc...,rt : different activities by bccf under embed ...,dengue
7478,3.306546e+09,2023-02-05 11:26:45+00:00,"b'dengue: 1 more dies, 5 patients hospitalised...","dengue: 1 more dies, 5 patients hospitalised\n...","dengue: 1 more dies, 5 patients hospitalised\n \n",dengue
7479,1.282360e+18,2023-02-05 11:14:11+00:00,"b""if only your name rhymed with dengue shock s...",if only your name rhymed with dengue shock syn...,if only your name rhymed with dengue shock syn...,dengue

In [23]:
df_dengue1=pd.DataFrame(df_dengue)

NameError: name 'df_dengue' is not defined

In [82]:
df_dengue1

,id,Time,Tweet,Processed_Tweets,tags
21658,276271211,2023-02-14 17:58:29+00:00,b'rt @davidulin: an honor to publish four new ...,b'rt:honorpublishfournewpoemsmorning.\n\n''den...,dengue
21659,28222035,2023-02-14 17:43:11+00:00,b'an honor to publish four new poems by @clmer...,b'anhonorpublishfournewpoemsmorning.\n\n''deng...,dengue
21660,1608303387103092736,2023-02-14 17:39:01+00:00,b'rt @kcoh999: dengue infections on the rise; ...,"b'rt:dengueinfectionsrise;outbreakclose,people...",dengue
21662,18649572,2023-02-14 17:16:51+00:00,b'all i listen to is alton ellis &amp; dengue ...,b'alllistenaltonellis&amp;denguedenguedengue.',dengue
21663,1089517380907266049,2023-02-14 17:09:51+00:00,b'@longchar_amenla it sucks but theres not muc...,"b'suckstheresmuch,livingalonedenguefarfaraw...",dengue
...,...,...,...,...,...
22754,705162643,2023-02-05 11:45:11+00:00,b'#nowplaying jump (mega banton) by dengue fev...,b'nowplayingjump(megabanton)denguefeverriddiml...,dengue
22755,63543042,2023-02-05 11:35:22+00:00,"b""rt @chris_c_chapman: blood counts still very...","b''rt:bloodcountsstilllow.startedgo,showsdengu...",dengue
22756,1273954059867701251,2023-02-05 11:30:20+00:00,b'rt @shukladeepak73: different activities by ...,b'rt:differentactivitiesbccfembedproject.\nmal...,dengue
22757,3306545726,2023-02-05 11:26:45+00:00,"b'dengue: 1 more dies, 5 patients hospitalised...","b'dengue:dies,patientshospitalised\ndenguebang...",dengue
22759,1282362054200958978,2023-02-05 11:14:11+00:00,"b""if only your name rhymed with dengue shock s...",b''namerhymeddengueshocksyndrome-inducingconsu...,dengue

In [52]:
df_fever1=pd.DataFrame(df_fever)

In [53]:
df_nausea1=pd.DataFrame(df_nausea)

In [54]:
df_sprain1=pd.DataFrame(df_sprain)

In [55]:
df_stroke1=pd.DataFrame(df_dengue)

In [56]:
df_anxiety1=pd.DataFrame(df_dengue)

In [57]:
df_flu1=pd.DataFrame(df_dengue)

In [58]:
df_obesity1=pd.DataFrame(df_obesity)

In [59]:
df_autism1=pd.DataFrame(df_autism)

In [83]:
df_dengue1=pd.DataFrame(df_dengue)

In [84]:
type(df_asthma1)

pandas.core.frame.DataFrame

In [89]:
(df_dengue['tags']=='dengue').sum()

730

In [88]:
df_dengue1

,id,Time,Tweet,Processed_Tweets,tags
21658,276271211,2023-02-14 17:58:29+00:00,b'rt @davidulin: an honor to publish four new ...,b'rt:honorpublishfournewpoemsmorning.\n\n''den...,dengue
21659,28222035,2023-02-14 17:43:11+00:00,b'an honor to publish four new poems by @clmer...,b'anhonorpublishfournewpoemsmorning.\n\n''deng...,dengue
21660,1608303387103092736,2023-02-14 17:39:01+00:00,b'rt @kcoh999: dengue infections on the rise; ...,"b'rt:dengueinfectionsrise;outbreakclose,people...",dengue
21662,18649572,2023-02-14 17:16:51+00:00,b'all i listen to is alton ellis &amp; dengue ...,b'alllistenaltonellis&amp;denguedenguedengue.',dengue
21663,1089517380907266049,2023-02-14 17:09:51+00:00,b'@longchar_amenla it sucks but theres not muc...,"b'suckstheresmuch,livingalonedenguefarfaraw...",dengue
...,...,...,...,...,...
22754,705162643,2023-02-05 11:45:11+00:00,b'#nowplaying jump (mega banton) by dengue fev...,b'nowplayingjump(megabanton)denguefeverriddiml...,dengue
22755,63543042,2023-02-05 11:35:22+00:00,"b""rt @chris_c_chapman: blood counts still very...","b''rt:bloodcountsstilllow.startedgo,showsdengu...",dengue
22756,1273954059867701251,2023-02-05 11:30:20+00:00,b'rt @shukladeepak73: different activities by ...,b'rt:differentactivitiesbccfembedproject.\nmal...,dengue
22757,3306545726,2023-02-05 11:26:45+00:00,"b'dengue: 1 more dies, 5 patients hospitalised...","b'dengue:dies,patientshospitalised\ndenguebang...",dengue
22759,1282362054200958978,2023-02-05 11:14:11+00:00,"b""if only your name rhymed with dengue shock s...",b''namerhymeddengueshocksyndrome-inducingconsu...,dengue

In [93]:
data['tags'].value_counts()

fever      750
nausea     750
sprain     750
stroke     750
anxiety    750
flu        750
obesity    750
autism     750
asthma     750
dengue     730
Name: tags, dtype: int64

In [94]:
data.to_csv('equalData.csv')