In [55]:
import pandas as pd
#using TextBlob
from textblob import TextBlob
#using vader
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [46]:
df=pd.read_csv('tweets2.csv')

In [47]:
df.head()

,Unnamed: 0,id,Time,Tweet,Location,split,tags,split_tweets,prep
0,0,312322346,2022-11-08 10:14:36+00:00,"b""Let's be honest; day two of a phase 1 cancer...",London,"['b""Let\'s', 'be', 'honest;', 'day', 'two', 'o...","[cancer, thyroidcancer, thyroid]","['honest', 'day', 'phase', 'cancer', 'trial', ...",honest day phase cancer trial look good cancer...
1,1,42296887,2022-11-08 10:15:07+00:00,b'Pembrolizumab: English Drugs Body Recommends...,Florida,"[""b'Pembrolizumab:"", 'English', 'Drugs', 'Body...",[],"['pembrolizumab', 'english', 'drug', 'bodi', '...",pembrolizumab english drug bodi recommend life...
2,2,1356818881063473157,2022-11-08 10:15:05+00:00,"b""RT @nettybgoode: Well, @ServicesGovAU are at...",NaN,"['b""RT', '@nettybgoode:', 'Well,', '@ServicesG...",[],"['rt', 'nettybgood', 'servicesgovau', 'day', '...",rt nettybgood servicesgovau day mum finish rad...
3,3,1570261324554293249,2022-11-08 10:15:04+00:00,b'@AlHosnApp where we can take session flu vac...,NaN,"[""b'@AlHosnApp"", 'where', 'we', 'can', 'take',...",[],"['alhosnapp', 'session', 'flu', 'vaccin', 'guid']",alhosnapp session flu vaccin guid
4,4,4836684705,2022-11-08 10:15:03+00:00,"b""RT @DFisman: Again, your immune system didn'...","Scotland, United Kingdom","['b""RT', '@DFisman:', 'Again,', 'your', 'immun...",[],"['rt', 'dfisman', 'immun', 'system', 'didn', '...",rt dfisman immun system didn flabbi flu season...

In [48]:
tweet_list=df['prep'].values.tolist()

In [49]:
print(tweet_list[:10])

['honest day phase cancer trial look good cancer thyroidcanc thyroid http uk jltrmml', 'pembrolizumab english drug bodi recommend life save cancer medicin http sgjpv http ofgb yw', 'rt nettybgood servicesgovau day mum finish radiat treatment ve drag centr xe xa', 'alhosnapp session flu vaccin guid', 'rt dfisman immun system didn flabbi flu season immun system work hard xe xa', 'rt mari collier az cancer wheel fortun predict money career love secret novemb oracl read gt http psn hbltbk lt xe xa', 'rt myesmo esmotat plummer ruth submit abstract amp shape futur cancer drug develop share xe xa', 'rt crapulaleonardo xc xa falei xc xbamera veze ma volto repetir grand mal grand xc xa ncer da humanidad atualment chama se extrema xe xa', 'rt ro arauz mi madr ha podido luchar la han dejado pelear contra el xc xa ncer diagnosticado se la ha llevado hilo xf xa xb ruego xe xa', 'novemb lung cancer awar month recognis sign symptom find xe xa http llgf rda']

In [50]:
#txtblob

In [52]:
def sentiment_analysis(df):
    
    def getSubjectivity(text):
        
        return TextBlob(text).sentiment.subjectivity
    def getPolarity(text):
        
        return TextBlob(text).sentiment.polarity
    df['TextBlob_Subjectivity']=df['prep'].apply(getSubjectivity)
    df['TextBlob_Polarity']=df['prep'].apply(getPolarity)
    def getAnalysis(score):
        if score < 0:
            return 'Negative'
        elif score == 0:
            return 'Neutral'
        else:
            return 'Positive'
        df['TextBlob_Analysis'] = df['TextBlob_Polarity'].apply(getAnalysis )
    return df

In [53]:
sentiment_analysis(df)

,Unnamed: 0,id,Time,Tweet,Location,split,tags,split_tweets,prep,TextBlob_Subjectivity,TextBlob_Polarity
0,0,312322346,2022-11-08 10:14:36+00:00,"b""Let's be honest; day two of a phase 1 cancer...",London,"['b""Let\'s', 'be', 'honest;', 'day', 'two', 'o...","[cancer, thyroidcancer, thyroid]","['honest', 'day', 'phase', 'cancer', 'trial', ...",honest day phase cancer trial look good cancer...,0.750000,0.650000
1,1,42296887,2022-11-08 10:15:07+00:00,b'Pembrolizumab: English Drugs Body Recommends...,Florida,"[""b'Pembrolizumab:"", 'English', 'Drugs', 'Body...",[],"['pembrolizumab', 'english', 'drug', 'bodi', '...",pembrolizumab english drug bodi recommend life...,0.000000,0.000000
2,2,1356818881063473157,2022-11-08 10:15:05+00:00,"b""RT @nettybgoode: Well, @ServicesGovAU are at...",NaN,"['b""RT', '@nettybgoode:', 'Well,', '@ServicesG...",[],"['rt', 'nettybgood', 'servicesgovau', 'day', '...",rt nettybgood servicesgovau day mum finish rad...,0.070833,-0.100000
3,3,1570261324554293249,2022-11-08 10:15:04+00:00,b'@AlHosnApp where we can take session flu vac...,NaN,"[""b'@AlHosnApp"", 'where', 'we', 'can', 'take',...",[],"['alhosnapp', 'session', 'flu', 'vaccin', 'guid']",alhosnapp session flu vaccin guid,0.000000,0.000000
4,4,4836684705,2022-11-08 10:15:03+00:00,"b""RT @DFisman: Again, your immune system didn'...","Scotland, United Kingdom","['b""RT', '@DFisman:', 'Again,', 'your', 'immun...",[],"['rt', 'dfisman', 'immun', 'system', 'didn', '...",rt dfisman immun system didn flabbi flu season...,0.541667,-0.291667
...,...,...,...,...,...,...,...,...,...,...,...
1575,1575,270679047,2022-11-08 10:00:14+00:00,b'Even your most long-term bonds you perhaps t...,montgomery ala,"[""b'Even"", 'your', 'most', 'long-term', 'bonds...",[],"['long', 'term', 'bond', 'grant', 'ne', 'cance...",long term bond grant ne cancer http xuupcgntd,0.400000,-0.050000
1576,1576,463838653,2022-11-08 10:00:14+00:00,b'Even your most long-term bonds you perhaps t...,freedom syria,"[""b'Even"", 'your', 'most', 'long-term', 'bonds...",[],"['long', 'term', 'bond', 'grant', 'ne', 'cance...",long term bond grant ne cancer http vbpja,0.400000,-0.050000
1577,1577,1221022807980638208,2022-11-08 10:00:14+00:00,b'RT @DDA_Denmark: THE DDEA BOARD OF DIRECTORS...,"Copenhagen, Denmark","[""b'RT"", '@DDA_Denmark:', 'THE', 'DDEA', 'BOAR...",[],"['rt', 'dda', 'denmark', 'ddea', 'board', 'dir...",rt dda denmark ddea board director nthe danish...,0.000000,0.000000
1578,1578,175605539,2022-11-08 10:00:14+00:00,b'Even your most long-term bonds you perhaps t...,NaN,"[""b'Even"", 'your', 'most', 'long-term', 'bonds...",[],"['long', 'term', 'bond', 'grant', 'ne', 'cance...",long term bond grant ne cancer http bylrqba ws,0.400000,-0.050000
1579,1579,281264917,2022-11-08 10:00:13+00:00,b'Even your most long-term bonds you perhaps t...,NaN,"[""b'Even"", 'your', 'most', 'long-term', 'bonds...",[],"['long', 'term', 'bond', 'grant', 'ne', 'cance...",long term bond grant ne cancer http xgfyzyhjvv,0.400000,-0.050000

In [54]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

### vader

In [57]:
analyser = SentimentIntensityAnalyzer()
data=df['prep'].map(lambda x: analyser.polarity_scores(x))

In [59]:
df2=pd.DataFrame.from_dict(data)

In [61]:
df2['prep'].apply(pd.Series)

        neg    neu    pos  compound
0     0.367  0.375  0.258   -0.5574
1     0.192  0.437  0.371    0.4767
2     0.137  0.863  0.000   -0.2263
3     0.394  0.606  0.000   -0.3818
4     0.250  0.750  0.000   -0.4588
...     ...    ...    ...       ...
1575  0.341  0.465  0.194   -0.4404
1576  0.341  0.465  0.194   -0.4404
1577  0.000  1.000  0.000    0.0000
1578  0.317  0.504  0.180   -0.4404
1579  0.341  0.465  0.194   -0.4404

[1580 rows x 4 columns]

In [ ]:
def class_label(df):
    def getLabel(score):
        if score < 0:
            return 'Negative'
        elif score == 0:
            return 'Neutral'
        else:
            return 'Positive'
    
    df['class']=df['split_tweets'].apply(getSubjectivity)
    
    def getAnalysis(score):
        if score < 0:
            return 'Negative'
        elif score == 0:
            return 'Neutral'
        else:
            return 'Positive'
        df['TextBlob_Analysis'] = df['TextBlob_Polarity'].apply(getAnalysis )
    return df